"""Initial migration1

Revision ID: 36263407e471
Revises: 1a685fb3971e
Create Date: 2024-09-29 11:55:05.239422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36263407e471'
down_revision: Union[str, None] = '1a685fb3971e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_time', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_user_created_time'), 'user', ['created_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_created_time'), table_name='user')
    op.drop_column('user', 'created_time')
    # ### end Alembic commands ###
