"""Initial migration

Revision ID: 7a3467c77a46
Revises: f791c93712f5
Create Date: 2024-10-01 10:33:43.433610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7a3467c77a46'
down_revision: Union[str, None] = 'f791c93712f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('ansver_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('test', sa.Column('number', sa.Integer(), nullable=False))
    op.add_column('test', sa.Column('status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'status')
    op.drop_column('test', 'number')
    op.drop_column('subject', 'ansver_value')
    # ### end Alembic commands ###
