"""Initial migration

Revision ID: 811d3e4fb669
Revises: 65a6f82348c2
Create Date: 2024-10-01 12:10:30.839040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '811d3e4fb669'
down_revision: Union[str, None] = '65a6f82348c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subject', 'subject_val',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subject', 'subject_val',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
