"""Initial migration

Revision ID: 9c140cb290c5
Revises: 811d3e4fb669
Create Date: 2024-10-01 12:17:54.613932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9c140cb290c5'
down_revision: Union[str, None] = '811d3e4fb669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_column('user', 'tg_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tg_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###
