"""Initial migration

Revision ID: f791c93712f5
Revises: 6dedab73dada
Create Date: 2024-10-01 10:32:15.215746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f791c93712f5'
down_revision: Union[str, None] = '6dedab73dada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('test', sa.Column('number', sa.Integer(), nullable=False))
    op.add_column('test', sa.Column('status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'status')
    op.drop_column('test', 'number')
    op.drop_column('subject', 'value')
    # ### end Alembic commands ###
